version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "15400:15400"
    volumes:
      - "./app:/code/app"
      - "./requirements.txt:/code/requirements.txt"
    command: ["uvicorn", "app.index:app", "--host", "0.0.0.0", "--port", "15400"]